<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/04/07 14:17:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=sysdba.cu6ggptbwlbt.us-west-2.rds.amazonaws.com;dbname=sysdba',
  'username' => 'root',
  'password' => 'chow20214',
  'name' => 'doctrine',
)),);
